### ISSUE TITLE
Contribute to the project (battery and sound)

### ISSUE THREAD

**Issue by VanGrx** [medusalix/xow#104]
Hello,

As I couldn't find any contact info, I am opening an issue as I want to provide support for battery and sound implementation as both branches are now missing on the project.

**Comment by medusalix** [comment]
Sure, I'd appreciate some help on these problems. There are already issues for both the battery and audio integration, so if you've got anything to add please do so on the respective issue thread. I've evaluated some ideas but I couldn't come up with a good solution to those things.
