### ISSUE TITLE
Add information about possible outdated libusb

### ISSUE THREAD

**Issue by mantheman** [medusalix/xow#107]
Under troubleshooting it says:

Mt76Exception: Failed to load firmware
Another driver might have already loaded the dongle's firmware. The dongle needs to be unplugged to reset its internal memory, followed by a restart of xow's systemd service.

Maybe add (and this is probably more likely at first) that it's because of an outdated libusb-1.0-0 package.
Confirmed using Ubuntu 14.04 with libusb-1.0-0 from 18.04.  (I also updated the toolchain to build xow, but that another topic).

**Comment by medusalix** [comment]
Thanks, I've added a notice to the README.
