### ISSUE TITLE
ERROR 127

### ISSUE THREAD

**Issue by dmobley0608** [medusalix/xow#113]
Trying to install onto a retropie build. During make BUILD=RELEASE I get the following error:

pi@retropie:~/xow $ make BUILD=RELEASE
curl -o driver.cab http://download.windowsupdate.com/c/msdownload/update/driver/drvs/2017/07/1cd6a87c-623f-4407-a52d-c31be49e925c_e19f60808bdcbfbd3c3df6be3e71ffc52e43261e.cab
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  195k  100  195k    0     0   956k      0 --:--:-- --:--:-- --:--:--  961k
cabextract -F FW_ACC_00U.bin driver.cab
make: cabextract: Command not found
make: *** [Makefile:39: firmware.bin] Error 127
pi@retropie:~/xow $

**Comment by medusalix** [comment]
> make: cabextract: Command not found

Install the `cabextract` tool, as noted in the `prerequisites` section of the README.
