### ISSUE TITLE
XOW not working on the latest stable manjaro release.

### ISSUE THREAD

**Issue by Walnut-dev** [medusalix/xow#127]
2020-10-19 02:21:51 INFO  - xow v0.5-17-gaf5b9d4 ©Severin v. W.
2020-10-19 02:21:51 INFO  - Waiting for device...
2020-10-19 02:21:52 INFO  - Wireless address: 62:45:b5:01:88:bb
2020-10-19 02:21:52 INFO  - Dongle initialized
2020-10-19 02:21:59 INFO  - Controller '1' connected
2020-10-19 02:21:59 INFO  - Device announced, product id: 02ea
2020-10-19 02:21:59 INFO  - Device announced, product id: 02f6
terminate called after throwing an instance of 'InputException'
  what():  Error adding key code: Invalid argument
zsh: abort      sudo xow

the issue is regarding a missing kernel module: uinput, i think atleast.
Regarding this issue wil it  be fixed by adding the uinput module with modeprobe to the kernel?

**Comment by transcengopher** [comment]
@Walnut-dev, your log seems very similar to what me and some other people have been getting in #118 (in fact, down to product ids in announcement events).

I suspect this might be due to controller itself, not the kernel modules.

**Comment by Walnut-dev** [comment]
@transcengopher, the problem is due to a missing kernel module called uinput. The kernel module seems loaded on most zen-kernels, which can be found here https://github.com/zen-kernel/zen-kernel

**Comment by kakra** [comment]
This doesn't make sense: If it works without headphones plugged, it would still use uinput and would throw the same error. However, there may be a difference between kernel versions where older version accept that "invalid argument".

**Comment by transcengopher** [comment]
@Walnut-dev, in lines between "Device announced 02ea" and "Device announced 02f6" the driver writes a great deal of stuff into the `uinput` channel , which works fine. This suggests you do have the module, and problem was in something else.
