### ISSUE TITLE
Running without root

### ISSUE THREAD

**Issue by pmiddend** [medusalix/xow#13]
Is this possible at all? It'd be safer if the service didn't need root, but just some privileged user.

**Comment by medusalix** [comment]
You could try creating an `udev` rule that changes the permissions of `/dev/uinput`. That seems to be the way [`Steam`](https://wiki.gentoo.org/wiki/Steam_Controller#Manual_udev) and [`python-uinput`](https://github.com/tuomasjjrasanen/python-uinput/blob/master/udev-rules/40-uinput.rules) solve this issue.

**Comment by pmiddend** [comment]
@medusalix Ah, thanks for the input. I've rewritten the service accordingly.
