### ISSUE TITLE
Problems connecting xbox controller to steam client

### ISSUE THREAD

**Issue by jonasskanoy** [medusalix/xow#135]
xow.service is running fine for me, the controller seem to be connected to the system. But, steam does not recognize the controller. Anyone that knows how to fix this?

![Xow status](https://user-images.githubusercontent.com/71043573/100487605-d270b300-3109-11eb-8af1-d1b77af43513.png)

![steam](https://user-images.githubusercontent.com/71043573/100487644-051aab80-310a-11eb-86e7-c32938a2a4a5.png)

**Comment by xsgb** [comment]
Hi, I can't try by myself but someone by chat reported me that it worked after unchecking "Xbox Configuration Support".

**Comment by JenkooTheLegitC** [comment]
Unchecked the "Xbox configuration support". Killed the steam daemon and repaired the controller. Still no connection. 

![error](https://user-images.githubusercontent.com/71043573/101987437-6313cb00-3c94-11eb-9ba9-dac0128fba24.png)
