### ISSUE TITLE
Just looking for confirmation on Audio status

### ISSUE THREAD

**Issue by Fredrum** [medusalix/xow#136]
Hi,

really nice job on this driver it worked a charm when I installed it on my Raspberry Pi 4 last night!
First time Iv'e got my xbox controller to work wirelessly with it. I have one of those dongle things.

I'm trying to find a wireless solution for Audio too so I just wanted to understand if I should expect this to work with xow as it currently is?

I did see a thread about audio that ended in mention of it being too much work to do for this software. I didn't completely get the context of the discussion so that's why I'm asking again here.

Again, Thanks a lot for making this and making it available!!
Cheers, Fred

**Comment by medusalix** [comment]
Hi @Fredrum,

Audio support for this driver was initially planned, but I've slowly realized that it is nearly impossible to implement *properly* without resorting to some kind of custom kernel driver.
Therefore, I've decided to put all my effort into the development of a kernel module that will eventually replace xow completely. Direct interaction with the kernel allows me to add all the requested features (upower integration, audio, etc.) to the new driver that I've been unable to implement for xow.

I hope this clears things up a bit :)
