### ISSUE TITLE
make BUILD=RELEASE error

### ISSUE THREAD

**Issue by Thinker08** [medusalix/xow#137]
make BUILD=RELEASE
g++  -o xow xow.o xow/xow.o dongle/mt76.o dongle/dongle.o dongle/usb.o controller/controller.o controller/input.o controller/gip.o utils/reader.o utils/log.o firmware.o -lpthread -lusb-1.0
/usr/bin/ld: cannot open output file xow: Je adresár
collect2: error: ld returned 1 exit status
make: *** [Makefile:29: xow] Error 1

**Comment by githubuserdefault** [comment]
I think you need these repositories

sudo apt-get install cabextract

sudo apt install libusb-1.0-0-dev build-essential

**Comment by Thinker08** [comment]
It's already working. My mistake, I used the wrong procedure from the internet. Thank you.
