### ISSUE TITLE
XOW seems to prevent Minecraft from launching

### ISSUE THREAD

**Issue by SveetPickle** [medusalix/xow#152]
I'm running Linux Mint 20, Installed XOW and it works fine except when I went to launch Minecraft I found the following error in the crash log. 

java.lang.IllegalStateException: GLFW error before init: [0x10004]Invalid axis in gamepad mapping 030000005e0400001907000000010000 (X360 Wireless Controller)

**Comment by kakra** [comment]
Do you have an active SDL mapping somewhere? You could try using the SDL2 gamepad tool to create a valid mapping and see if it helps. If you're using antimicro for Minecraft, you may need to redo the mapping for it. Maybe you're using a mod that supports gamepads directly without resorting to antimicro? You could try disabling it. This could give a better clue where to look for the problem.
