### ISSUE TITLE
Model 1790 correctly working

### ISSUE THREAD

**Issue by LordDaveTheKind** [medusalix/xow#155]
Hello,
I'm here to report that also the model 1790 is perfectly working. No issues found in any videogame or environment.

**Comment by prafiny** [comment]
Have you tried the audio output ? Doesn't seem to work for me (no sink in pulseaudio)

**Comment by medusalix** [comment]
Model 1790 is the slim version of the wireless dongle and has always been compatible with xow. Audio is not supported by xow.
