### ISSUE TITLE
make BUILD=RELEASE

### ISSUE THREAD

**Issue by skepticalcow** [medusalix/xow#160]
I'm sure it is a simple fix, but I am new to Linux.
When I type "make BUILD=RELEASE" I get "make: *** No targets specified and no makefile found. Stop." Please help a noob out.

**Comment by medusalix** [comment]
@skepticalcow I assume you ran `git clone` to download a local copy of xow. You have to execute `cd xow` to change into the `xow` directory before running `make BUILD=RELEASE` to compile the project.
