### ISSUE TITLE
make: *** [Makefile:39: firmware.bin] Error 127

### ISSUE THREAD

**Issue by eduardo989** [medusalix/xow#165]
I get this error, I read I should try with build=essential and didn't work also used the buld=release and got the same error

make BUILD=essential
g++  -Wall -Wpedantic -std=c++11 -MMD -MP  -DVERSION=\"v0.5-25-g8dd0888\" -c -o xow.o xow.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP  -DVERSION=\"v0.5-25-g8dd0888\" -c -o dongle/mt76.o dongle/mt76.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP  -DVERSION=\"v0.5-25-g8dd0888\" -c -o dongle/dongle.o dongle/dongle.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP  -DVERSION=\"v0.5-25-g8dd0888\" -c -o dongle/usb.o dongle/usb.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP  -DVERSION=\"v0.5-25-g8dd0888\" -c -o controller/controller.o controller/controller.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP  -DVERSION=\"v0.5-25-g8dd0888\" -c -o controller/input.o controller/input.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP  -DVERSION=\"v0.5-25-g8dd0888\" -c -o controller/gip.o controller/gip.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP  -DVERSION=\"v0.5-25-g8dd0888\" -c -o utils/reader.o utils/reader.cpp
g++  -Wall -Wpedantic -std=c++11 -MMD -MP  -DVERSION=\"v0.5-25-g8dd0888\" -c -o utils/log.o utils/log.cpp
curl -o driver.cab http://download.windowsupdate.com/c/msdownload/update/driver/drvs/2017/07/1cd6a87c-623f-4407-a52d-c31be49e925c_e19f60808bdcbfbd3c3df6be3e71ffc52e43261e.cab
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  195k  100  195k    0     0   158k      0  0:00:01  0:00:01 --:--:--  158k
cabextract -F FW_ACC_00U.bin driver.cab
make: cabextract: Command not found
make: *** [Makefile:39: firmware.bin] Error 127

**Comment by kakra** [comment]
Just FTR, people getting this error need to install cabextract.
