### ISSUE TITLE
make: *** [Makefile:29: xow] Fehler 1

### ISSUE THREAD

**Issue by akiro03** [medusalix/xow#174]
when I run  make BUILD=RELEASE i get the following error

g++  -o xow xow.o controller/controller.o controller/gip.o controller/input.o dongle/dongle.o dongle/mt76.o dongle/usb.o utils/log.o utils/reader.o xow/xow.o firmware.o -lpthread -lusb-1.0
/usr/bin/ld: cannot open output file xow: Is a directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:29: xow] Error 1

pls help

**Comment by Tignass** [comment]
I had the same error, I deleted the xow folder (I had other errors before) and start from scratch and it now worked
