### ISSUE TITLE
OpenRC Support

### ISSUE THREAD

**Issue by mrturcot** [medusalix/xow#179]
Hello, wondering if OpenRC will be supported in the future, or if thats planned.

Many thanks

**Comment by transcengopher** [comment]
There's a https://github.com/medusalix/xow/issues/102, with related PR attached to it. Would that suffice?

**Comment by mrturcot** [comment]
> There's a #102, with related PR attached to it. Would that suffice?

Seems there is some sort of resolution, however im not sure how to implement...

**Comment by mrturcot** [comment]
xone
