### ISSUE TITLE
Uses 100% one CPU thread

### ISSUE THREAD

**Issue by zaryuta** [medusalix/xow#181]
Uses 100% of one CPU thread. Tried on Manjaro kernel 5.13 and PopOs kernel 5.12.

**Comment by Galcian79** [comment]
I patched libusb from source, i confirm now it works as intended.

**Comment by sorgelig** [comment]
@Galcian79 
which patch you've used and to which libusb version?

**Comment by Galcian79** [comment]
> @Galcian79
> which patch you've used and to which libusb version?

The version i patched is the latest 1.0.24
This is the upstreamed patch https://github.com/libusb/libusb/commit/32a22069428cda9d63aa666e92fb8882a83d4515

**Comment by sorgelig** [comment]
i see.. 
i think it's better to compile statically with older libusb and leave current libusb version in system for stability purpose. At least till 1.0.25 release.

**Comment by medusalix** [comment]
Duplicate of #141.
