### ISSUE TITLE
Error when trying to make BUILD=RELEASE

### ISSUE THREAD

**Issue by R0bert0r** [medusalix/xow#186]
Hello, 
          Im reciving the followng error when trying to make the file and im not sure how to fix it: 

```
tom@tom-AX370:~/Downloads/xow$` make BUILD=RELEASE
g++  -Wall -Wpedantic -std=c++11 -MMD -MP -O3 -DVERSION=\"v0.5-27-g700529b\" -c -o xow.o xow.cpp
In file included from xow.cpp:21:
dongle/usb.h:29:10: fatal error: libusb-1.0/libusb.h: No such file or directory
   29 | #include <libusb-1.0/libusb.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:32: xow.o] Error `1
```

Please help me figure out the error. 

thanks

**Comment by kakra** [comment]
Install libusb-dev or libusb-headers

**Comment by R0bert0r** [comment]
> b

I installed libusb-dev but im still getting the same erroe when running make BUILD=RELEASE

```
make BUILD=RELEASE
g++  -Wall -Wpedantic -std=c++11 -MMD -MP -O3 -DVERSION=\"v0.5-27-g700529b\" -c -o xow.o xow.cpp
In file included from xow.cpp:21:
dongle/usb.h:29:10: fatal error: libusb-1.0/libusb.h: No such file or directory
   29 | #include <libusb-1.0/libusb.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:32: xow.o] Error 1

```

**Comment by williamtcastro** [comment]
@nick-prat thanks, runing `sudo apt install libusb-1.0-0-dev` worked for me.

**Comment by trewest** [comment]
for folks on fedora, `sudo dnf install -y libusbx-devel`

**Comment by fjrider** [comment]
Love the controller driver, thank you!

On Linux Mint (Ubuntu Base) I could not get BUILD=RELEASE to run.

I found out I had to install g++ (not sure what that is or does but then it worked).
