### ISSUE TITLE
Mapping of X and Y buttons is mirrored 

### ISSUE THREAD

**Issue by NoXPhasma** [medusalix/xow#2]
The X and Y buttons are mirrored, X is recognized as Y and vis versa. I guess there is something mixed up in the code :)

**Comment by medusalix** [comment]
Buttons are mapped according to the Linux docs. So the DPAD is mapped using BTN_NORTH, BTN_EAST, BTN_SOUTH and BTN_WEST. Unfortunately, it looks like BNT_NORTH is [equivalent](https://github.com/torvalds/linux/blob/737214515d7965485c52bc5f869e57a6976cf216/include/uapi/linux/input-event-codes.h#L386) to BTN_X on Linux. I'm not sure which button scheme I should be following.

**Comment by NoXPhasma** [comment]
The X and Y buttons definitely doesn't follow what the XBOX One S controller is mapped with xpad (wired), hid_microsoft (bluetooth) or xpadneo (blietooth). No matter what game/tool I use, it's wrong in all of them.

**Comment by medusalix** [comment]
Should we just ignore the docs and map the buttons using BTN_A, BTN_B, BTN_X and BTN_Y?

**Comment by NoXPhasma** [comment]
I think we should go the same route as xpadneo and xpad go. As this would make sure it's recognized the same way and we don't run into any issues.

I've also just found out that the DPAD won't be recognized in games as well. You've mapped it as buttons 11-14, but apparently with xpad it's mapped as axes 6 and 7.

**Comment by NoXPhasma** [comment]
Your commit (https://github.com/medusalix/xow/commit/502abcf6698e0fc91129c6e9e2dfc4c82bf4188e) fixed the wrong Y and X mapping. Now only the DPAD is left and the controller works as intended :)

**Comment by medusalix** [comment]
The latest commit should've now fixed the DPAD.

**Comment by NoXPhasma** [comment]
It does, the mapping is now as expected.
