### ISSUE TITLE
xow uses 50% CPU on idle

### ISSUE THREAD

**Issue by zac-davis** [medusalix/xow#200]
Ubuntu version 21.10
I'm not too sure how else to elaborate on this, just that with nothing connected and dongle plugged in, xow uses 42% to 51% of my CPU when computer is idle. Usage drops when dongle is unplugged

**Comment by shaunblyde** [comment]
I assume it is this: https://github.com/libusb/libusb/issues/913
Fixed in libusb 1.0.25

**Comment by zac-davis** [comment]
> I assume it is this: [libusb/libusb#913](https://github.com/libusb/libusb/issues/913) Fixed in libusb 1.0.25

Thanks! I didn't get around to actually trying this fix, since apparently my MSI network card became supported sometime between when I first started using xow and now. ie. removing the dongle is all I needed to do
