### ISSUE TITLE
fix bug in install instructions 

### ISSUE THREAD

**Issue by SimeonEhrig** [medusalix/xow#203]
At point 3 of the install instruction, the `xow-get-firmware.sh` should be executed. But at this point, the script is not available, because it is generated by the `make install` command via a copy of the `firmware.sh` script.

Ether the order of the install instructions needs to be changed or instruction 3 needs to be changed to:

```bash
chmod +x firmware.sh
sudo ./firmware.sh
```

**Comment by medusalix** [comment]
Thanks for the report, I've adjusted the order of the installation instructions in 949c8c09949944d0c53aa9871a6f5a6170a29f69.
