### ISSUE TITLE
Project Support

### ISSUE THREAD

**Issue by rwilliams** [medusalix/xow#22]
@medusalix Would it be possible to get an English paypal link too and you might be interested in creators.brave.com you can link your github to it to accept BAT tips.

**Comment by rwilliams** [comment]
I'm an idiot :P

**Comment by rwilliams** [comment]
Ok. Would it be possible to get an English paypal link too and you might be interested in creators.brave.com you can link your github to it to accept BAT tips.

**Comment by medusalix** [comment]
I assumed PayPal would allow donations in all currencies and convert those to the corresponding value in EUR (minus the fees). Is that not the case?

I took a look at Brave Creators, but they require you to share all your personal information with their payment processor, which I don't really want to do. I'm fine with PayPal at the moment.

**Comment by rwilliams** [comment]
Euros is not the problem. Trying to beat the recapcha boss in a foreign
language is.

**Comment by rwilliams** [comment]
Ok, it looks like your email is at the top of the current link provided. Right now that link is in German and google translate doesn't seem to work on it. The recaptcha boss in particular is hard, though i guess i could manually paste the phrase they are looking for in google translate.

**Comment by medusalix** [comment]
> Right now that link is in German

Ah, so the problem is the German page and not the actual payment process.
From a quick google search it seems like other projects fixed this issue by append `&lc=US` to the donation link. Could you please try if that works? Thank you very much for your donation 😃.

**Comment by rwilliams** [comment]
That didn't work. This did.
https://www.paypal.com/donate/?token=P-T6Gs5p3CPBmtOx2B1tpTm15mASHgLFUXw5JEKPghrua1vELEWJ3-coks3NDtdQEXcjB0&country.x=US&locale.x=US

**Comment by medusalix** [comment]
That's the link PayPal redirects me to when I click https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=PLN6F3UGS37DE&lc=US. It works just fine on my system, maybe you need to clear the cache/cookies.

**Comment by rwilliams** [comment]
I didn't append the `&lc=US` to your link, I guess i misunderstood and appended it to the generated link like an idiot. Good to go now.
