### ISSUE TITLE
Make the driver be DKMS compatible in the future

### ISSUE THREAD

**Issue by DatCrazyDelphox** [medusalix/xow#34]
Hi, I would know if you're interested in eventually convert the driver to a dkms package later on, because it wouldn't need to be linked with systemd services and would work on Linux out of the box as a (almost) integrated driver. 

Also, it would do great as a integrated driver of my gaming-focused kernel fork

It doesn't need to be done now, but I would like to get an idea from you

**Comment by medusalix** [comment]
Please see issue #36. xow is deliberatly designed as a user space driver and not as a kernel module. Obviously, I can't prevent people from rewriting and creating a kernel driver, but that would literally be no improvement over the user space version.
