### ISSUE TITLE
Upstream it to the kernel

### ISSUE THREAD

**Issue by yodatak** [medusalix/xow#36]
Thanks for this awsome work , do you think that it will posible to upstream it with help from the one who get xbox one controler into the kernel ?

**Comment by medusalix** [comment]
I don't think so, as xow is not a kernel driver. It runs completely in user space and is not designed to be used as a kernel module. Doing so would require a full rewrite of xow (in C). Getting drivers upstreamed is a whole different story, not even [xpadneo](https://github.com/atar-axis/xpadneo/issues/44) is upstreamed yet. There are multiple reasons for xow to run in user space:

1. Stability (if xow crashes your system will crash too)
2. Maintenance (every single new update would have to be upstreamed)
3. Support (why does feature xy work on kernel 5.5 but not on 5.4?)

It doesn't make sense to create kernel drivers, unless there's *no other way* do access the hardware interfaces you want to use. In the case of xow, we've got `libusb` and `uinput` which allow us to stay 100% in user space.
