### ISSUE TITLE
Controller keeps disconnecting and then reconnecting

### ISSUE THREAD

**Issue by PopeRigby** [medusalix/xow#43]
I'm having an issue where at seemly random points, the Xbox symbol will flash for a few seconds (indicating that the controller is disconnected) and then go solid again (indicating that it has reconnected. At first, I thought the batteries were dying, but I switched them out and checked their charge, so that wasn't the issue. I've only had this happen in the Witcher 3, but that's the only game I've tested it on. Another thing that might be important, when I'm holding down the left stick to run, it keeps running while it's disconnected, and then I have control again when it reconnects.

**Comment by NoXPhasma** [comment]
Please try the latest master, it should fix that behaviour.

**Comment by PopeRigby** [comment]
Seems to be fixed. Thanks!
