### ISSUE TITLE
Installing on linux mint 19.3

### ISSUE THREAD

**Issue by Kwik117** [medusalix/xow#46]
It doesnt seem to be installing, Not sure why. Im a novice linux user, so not really familiar with error codes and all that in terminal. Just wondering if there is a different set of commands for my version of linux.

**Comment by WernerAUT** [comment]
i built it today in Mint 19.3 you need to do the following
apt install libusb-1.0-0-dev build-essential
after that follow the guide
it could also be that you miss git so for that you also have todo
apt install git

**Comment by Kwik117** [comment]
Thanks, trying it now.

**Comment by Kwik117** [comment]
your a genius thank you. its working great.
