### ISSUE TITLE
Boot of PI4 sometimes does not connect controllers

### ISSUE THREAD

**Issue by mooock** [medusalix/xow#58]
I run on a fully updated retro bliss image from Vman. and have installed XOW, all other controller drivers has been uninstalled and have a xbox elite and xbox one s controller connected. sometimes after a full reboot with power off, the controller won't connect, then i can reboot once again and suddenly it works fine.

**Comment by medusalix** [comment]
Hi, sorry for my late reply, I was pretty busy with all the other issues that suddenly appeared. Can you post the logs of xow's service after one of the occasions where they don't connect? Please make sure you're running the latest version too.

**Comment by mooock** [comment]
After the latest update with the wifi channel fix, i have not seen issues when booting as well. everything has really worked great out

**Comment by medusalix** [comment]
That's great! I'm trying my best to make xow as reliable as possible :smiley:.

**Comment by mooock** [comment]
I have also tested it with a new and old dongle, and elite and non elite
