### ISSUE TITLE
Debian package link showing error.

### ISSUE THREAD

**Issue by Neverest** [medusalix/xow#65]
Since I am going to upgrade to 20.04 soon, I decided to check the debian package from the readme info, but it seems to not exist:

![image](https://user-images.githubusercontent.com/13340767/81445569-1dfc4900-9147-11ea-9f02-165cc0fea1ea.png)

Anything I did wrong or is missing?

**Comment by medusalix** [comment]
It was apparently removed because the license of the `firmware.bin` file is still unclear (see [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954876) issue on Debian's mailing list). I've requested a comment from MediaTek, but they didn't bother to answer (see #15).

**Comment by samueloph** [comment]
Yes, I had to ask for the removal because of the licensing issue, after that is solved it won't take much for the package to go back to the repositories, but for now we can't distribute it because it could cause issues for both Debian and upstream.

**Comment by medusalix** [comment]
I've removed the link to the Debian package from the README for now. Still no response from MediaTek, I'll update issue #15 when they get back to me.
