### ISSUE TITLE
Non-standard service file location

### ISSUE THREAD

**Issue by viggy96** [medusalix/xow#66]
/usr/etc/systemd/system/xow.service does not appear to be a location that systemd looks for service files. So when you try to run the service, systemd does not find the service file that the user is referring to. I believe that this issue occurs due to 3ce97b6.

**Comment by x4mers** [comment]
Looking at the Makefile, the install script says xow.service should be installed to /lib/systemd/system.

That's where the script installed it to on my system.

**Comment by medusalix** [comment]
I've read through `systemd`'s [documentation](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path) and noticed that `/lib` (or `/usr/lib` for that matter) is actually reserved for *System units installed by the distribution package manager*, so I decided to change all paths to use `/etc` instead (which in my opinion makes more sense).
If I run `sudo make install` it installs the service unit to `/etc/systemd/system` as expected, so I don't know why you're getting `/usr/etc/systemd/system` instead. Did you set the `DESTDIR` variable to `/usr`?

**Comment by viggy96** [comment]
@medusalix It was the PKGBUILD in the AUR that was the issue. Thanks for your help, and great work.

**Comment by medusalix** [comment]
@viggy96 Ah, that explains why it worked fine for me. Sorry for the trouble caused.
