### ISSUE TITLE
Error in installation if p7zip-full is not installed

### ISSUE THREAD

**Issue by Nathorr** [medusalix/xow#70]
I got the following error when installing:

7z x driver.cab FW_ACC_00U.bin > /dev/null
/bin/sh: 1: 7z: not found
make: *** [Makefile:36: firmware.bin] Error 127

I didn't have p7zip-full installed as it is not installed in Raspbian Buster by default. Solved after installing p7zip-full.

p7zip-full should be added to the prerequisites list.

**Comment by dodgypast** [comment]
On arch I have p7zip installed, but still getting the same error

**Comment by medusalix** [comment]
Good catch :+1:. I originally assumed that `7zip` came preinstalled with most Linux distributions. As that's apparently not the case, I have now switched to `cabextract` and added it to the list of prerequisites (together with `curl`). These tools are fortunately only required once for the firmware download and extraction, so you can remove them afterwards.
