### ISSUE TITLE
Ebuild for gentoo

### ISSUE THREAD

**Issue by dsiggi** [medusalix/xow#75]
Hi,
first of all thank you for your great work. Finally I can use my controller under linux wireless.

I write an ebuild for gentoo linux. Feel free to link it in your README.

[https://github.com/dsiggi/dsiggis-gentoo-overlay/tree/master/games-util/xow](https://github.com/dsiggi/dsiggis-gentoo-overlay/tree/master/games-util/xow)

**Comment by medusalix** [comment]
Thanks. I've added it to the README.
