### ISSUE TITLE
Program crash after plug audio jack into xbox controller

### ISSUE THREAD

**Issue by blythe-ren** [medusalix/xow#91]
Hi,
Recently I've bought a new xbox controller. I am happy to find a solution that makes my linuxmint LXDE can work with this game controller properly through xow program. very appreciate all authors effort.

My controller is wireless version. I didn't test blutooth cause my mainboard didn't support.

After plug headset into controller (using wireless connectivity), I found the xbox-led on controller start blinking.  "ps" command shown xow program disappear

therefore I trigger program manually and program dump message below

2020-06-18 14:33:04 INFO  - xow v0.5-6-g9e86c52 ©Severin v. W.
2020-06-18 14:33:04 INFO  - Waiting for device...
2020-06-18 14:33:05 INFO  - Wireless address: 62:45:bd:01:8d:4b
2020-06-18 14:33:05 INFO  - Dongle initialized
2020-06-18 14:33:06 INFO  - Controller '1' connected
2020-06-18 14:33:07 INFO  - Device announced, product id: 02ea
2020-06-18 14:33:07 INFO  - Device announced, product id: 02f6
terminate called after throwing an instance of 'InputException'
  what():  Error adding key code: Invalid argument
Aborted (core dumped)

and

another question is

when plug micro-usb only, xbox controller also no work. (didn't see led light up just like at win 10 environment)

any body can help me ? I've been check that it should be no issue on audio jack

**Comment by flopglop** [comment]
Hi.
I can confirm this also happens on manjaro kde, however my controller works out if the box when plugged in, and the linux kernel supports wired xbox controllers out of the box. Try using another usb cable?

**Comment by medusalix** [comment]
Headsets are currently not supported, see issue #4. USB connectivity is implemented solely in the kernel.

**Comment by blythe-ren** [comment]
yeah, I've been test under win 10 environment. The cable is OK  . Seems my new controller have good function properly in all 3 connectivity way. I also update to the xbox controller to newest driver ..

**Comment by blythe-ren** [comment]
`Linux b-pc 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`

have no idea why usb can't work ..

**Comment by blythe-ren** [comment]
> Headsets are currently not supported, see issue #4. USB connectivity is implemented solely in the kernel.

thanks medusalix,
I also want to report a problem. Program exit when I plug out my wireless receiver.

**Comment by medusalix** [comment]
> Program exit when I plug out my wireless receiver.

You need to install xow as a system service as described in the README. I wouldn't recommend running xow manually.

**Comment by blythe-ren** [comment]
thanks .. I have no question
