### ISSUE TITLE
Can use a fake xbox one Joystick and dongle

### ISSUE THREAD

**Issue by zeunus** [medusalix/xow#96]
Hi, i have this control
![joystick](https://user-images.githubusercontent.com/67354990/85496153-de2fda80-b5a9-11ea-8d1a-7bb1b6455264.jpg)
Is It possible 

Is it possible to run it with the driver?
I accompany dmesg
![Uploading shanwan.png…]()

I probe it and no results :c

**Comment by zeunus** [comment]
![shanwan](https://user-images.githubusercontent.com/67354990/85496336-1d5e2b80-b5aa-11ea-8e33-7b48c9e70707.png)

**Comment by medusalix** [comment]
I don't think it's compatible. It's probably a completely different dongle only made to look like the original one. I don't provide support for counterfeit Xbox One controllers.
